# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
model:
  multi_step: 2
  dev_batch_size: 512
  train_batch_size: 128
slbo:
  n_stages: 100
  n_iters: 20
  n_model_iters: 100
  n_policy_iters: 40
TRPO:
  ent_coef: 0.005
